#!/bin/zsh
REPO_ROOT="${0:A:h}"
DICTIONARY="${REPO_ROOT}/.affin.ko.dictionary"
AFFINITY_APP="/Applications/Affinity.app"

echo "→ Affinity.app을 종료합니다."
pkill -f "Affinity"

echo "→ ko.lproj 폴더를 생성합니다."

test -d "${AFFINITY_APP}/Contents/Resources/ko.lproj"
if [[ $? -eq 1 ]]; then
  mkdir "${AFFINITY_APP}/Contents/Resources/ko.lproj"
fi

test -d "${AFFINITY_APP}/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/ko.lproj"
if [[ $? -eq 1 ]]; then
  mkdir "${AFFINITY_APP}/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/ko.lproj"
fi

echo "→ Check Update"
cd "${REPO_ROOT}"
git pull

ENGPATH="${AFFINITY_APP}/Contents/Resources/en-US.lproj/"
KORPATH="${AFFINITY_APP}/Contents/Resources/ko.lproj/"
FILECOUNT=$(ls -a "${ENGPATH}" | grep "strings" | sed -n "=" | tail -n "1")
for ((i = 1; i <= ${FILECOUNT}; i++)); do
  FILENAME=$(ls "${ENGPATH}" | /usr/bin/sed -n "${i}p")
  printf "→ ${i}/${FILECOUNT}\t${FILENAME}\n"
  iconv -f UTF-16LE -t UTF-8 "${ENGPATH}${FILENAME}" >"${KORPATH}${FILENAME}.temp"
  sed -f "${DICTIONARY}" "${KORPATH}${FILENAME}.temp" >"${KORPATH}${FILENAME}"
done

ENGFPATH="${AFFINITY_APP}/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/en-US.lproj/"
KORFPATH="${AFFINITY_APP}/Contents/Frameworks/libcocoaui.framework/Versions/A/Resources/ko.lproj/"
FILECOUNT=$(ls -a "${ENGFPATH}" | grep "strings" | sed -n "=" | tail -n "1")
for ((i = 1; i <= ${FILECOUNT}; i++)); do
  FILENAME=$(ls "${ENGFPATH}" | /usr/bin/sed -n "${i}p")
  printf "→ ${i}/${FILECOUNT}\t${FILENAME}\n"
  iconv -f UTF-16LE -t UTF-8 "${ENGFPATH}${FILENAME}" >"${KORFPATH}${FILENAME}.temp"
  sed -f "${DICTIONARY}" "${KORFPATH}${FILENAME}.temp" >"${KORFPATH}${FILENAME}"
done

open -a "${AFFINITY_APP}"
